name: CI Test

on:
  push:
    branches: [ esp8266 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Hello World
      run: echo "Hello from GitHub Actions!"
